name: publish-snapshot
on:
  push:
    branches:
      - master

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Publish snapshot
        run: maven publish '-Dversion=${{ github.sha }}-SNAPSHOT' '-DaltDeploymentRepository=snapshot-repo::https://nexus.twelveiterations.com/repository/maven-snapshots/' '-Dusername=${{ secrets.NEXUS_USER }}' '-Dpassword=${{ secrets.NEXUS_PASSWORD }}'