name: publish-release
on:
  push:
    tags:
      - '*'

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          server-id: release-repo
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish release
        run: mvn deploy '-Dversion=${{ github.ref_name }}' '-DaltDeploymentRepository=release-repo::default::https://nexus.twelveiterations.com/repository/maven-releases/'
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}